### PR TITLE
Fixed the Package.swift file used in the makefile

### PR DESCRIPTION
**Pull request by woolie**
I apologize for wasting your time. I made the mistake of testing in Xcode and not testing the Makefile which is what brew is using to distribute the binary.

These changes fix the issue. Thanks for your patience

### CODE REVIEW

**Comment by davidahouse** [comment]
No problem. Sorry I don't have time right now to help test these changes. But I can hit the merge buttons. :)

**Comment by davidahouse** [comment]
I updated the version to 0.6.1 also

**Comment by woolie** [comment]
Would it be possible to bump the home-brew recipe to point to the 0.6.1 please?


W.

**Comment by davidahouse** [comment]
Done!

**Pull request merged**
